GEMINI_API_KEY="AIzaSyDP7JxIi0E-SXs4sTBdOQsvnjy0fMOq2iI"
YOUTUBE_API_KEY="AIzaSyBRq0ljZ3bFFCasSsofLJU-ahLbHu6kvKY"

#Collect user & pw
MONGO_URI = "mongodb+srv://streamlit_user:12345@cluster0.xxxxx.mongodb.net/?retryWrites=true&w=majority"
